version: "3.4"

services:
  admin:
    build:
      context: ./
      dockerfile: admin/Dockerfile
    restart: unless-stopped
    environment:
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_ADMIN_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_ADMIN_PASSWORD}
    ports:
      - "5602:5601"
  guest:
    build:
      context: ./
      dockerfile: guest/Dockerfile
    restart: unless-stopped
    environment:
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_ADMIN_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_ADMIN_PASSWORD}
    ports:
      - "5601:5601"
  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    environment:
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_GUEST_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_GUEST_PASSWORD}
    ports:
      - "80:80"
